version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sel_diagnostic_app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=diagnostic_center
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sel_network

  db:
    image: mariadb:10.11
    container_name: sel_diagnostic_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: diagnostic_center
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./diagnostic_center.sql:/docker-entrypoint-initdb.d/diagnostic_center.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sel_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: sel_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - sel_network

networks:
  sel_network:
    driver: bridge

volumes:
  db_data:
    driver: local
